// This is a Zig translation of the Python code that defines a mapping from MODEL_TENSOR to string sequences.
// The original Python relies on enums and dictionaries with tuple values, translated here using enums and struct literals.

const std = @import("std");

pub const ModelArch = enum {
    LLAMA,
    DECI,
    FALCON,
    BAICHUAN,
    GROK,
    GPT2,
    GPTJ,
    GPTNEOX,
    MPT,
    STARCODER,
    REFACT,
    BERT,
    NOMIC_BERT,
    JINA_BERT_V2,
    BLOOM,
    STABLELM,
    QWEN,
    QWEN2,
    QWEN2MOE,
    QWEN2VL,
    PHI2,
    PHI3,
    PLAMO,
    CODESHELL,
    ORION,
    INTERNLM2,
    MINICPM,
    MINICPM3,
    GEMMA,
    GEMMA2,
    STARCODER2,
    RWKV6,
    MAMBA,
    XVERSE,
    COMMAND_R,
    COHERE2,
    DBRX,
    OLMO,
    OLMO2,
    OLMOE,
    OPENELM,
    ARCTIC,
    DEEPSEEK,
    DEEPSEEK2,
    CHATGLM,
    BITNET,
    T5,
    T5ENCODER,
    JAIS,
    NEMOTRON,
    EXAONE,
    GRANITE,
    GRANITE_MOE,
    CHAMELEON,
    WAVTOKENIZER_DEC,
};

pub const ModelArchNames = struct {
    const Self = @This();

    pub const map = std.enums.EnumMap(ModelArch, []const u8).init(.{
        .LLAMA = "llama",
        .DECI = "deci",
        .FALCON = "falcon",
        .BAICHUAN = "baichuan",
        .GROK = "grok",
        .GPT2 = "gpt2",
        .GPTJ = "gptj",
        .GPTNEOX = "gptneox",
        .MPT = "mpt",
        .STARCODER = "starcoder",
        .REFACT = "refact",
        .BERT = "bert",
        .NOMIC_BERT = "nomic-bert",
        .JINA_BERT_V2 = "jina-bert-v2",
        .BLOOM = "bloom",
        .STABLELM = "stablelm",
        .QWEN = "qwen",
        .QWEN2 = "qwen2",
        .QWEN2MOE = "qwen2moe",
        .QWEN2VL = "qwen2vl",
        .PHI2 = "phi2",
        .PHI3 = "phi3",
        .PLAMO = "plamo",
        .CODESHELL = "codeshell",
        .ORION = "orion",
        .INTERNLM2 = "internlm2",
        .MINICPM = "minicpm",
        .MINICPM3 = "minicpm3",
        .GEMMA = "gemma",
        .GEMMA2 = "gemma2",
        .STARCODER2 = "starcoder2",
        .RWKV6 = "rwkv6",
        .MAMBA = "mamba",
        .XVERSE = "xverse",
        .COMMAND_R = "command-r",
        .COHERE2 = "cohere2",
        .DBRX = "dbrx",
        .OLMO = "olmo",
        .OLMO2 = "olmo2",
        .OLMOE = "olmoe",
        .OPENELM = "openelm",
        .ARCTIC = "arctic",
        .DEEPSEEK = "deepseek",
        .DEEPSEEK2 = "deepseek2",
        .CHATGLM = "chatglm",
        .BITNET = "bitnet",
        .T5 = "t5",
        .T5ENCODER = "t5encoder",
        .JAIS = "jais",
        .NEMOTRON = "nemotron",
        .EXAONE = "exaone",
        .GRANITE = "granite",
        .GRANITE_MOE = "granitemoe",
        .CHAMELEON = "chameleon",
        .WAVTOKENIZER_DEC = "wavtokenizer-dec",
    });

    pub fn get(arch: ModelArch) []const u8 {
        return map.get(arch).?;
    }
};
pub const ModelTensor = enum {
    TOKEN_EMBD,
    TOKEN_EMBD_NORM,
    TOKEN_TYPES,
    POS_EMBD,
    OUTPUT,
    OUTPUT_NORM,
    ROPE_FREQS,
    ROPE_FACTORS_LONG,
    ROPE_FACTORS_SHORT,
    ATTN_Q,
    ATTN_K,
    ATTN_V,
    ATTN_QKV,
    ATTN_OUT,
    ATTN_NORM,
    ATTN_NORM_2,
    ATTN_OUT_NORM,
    ATTN_POST_NORM,
    ATTN_ROT_EMBD,
    FFN_GATE_INP,
    FFN_GATE_INP_SHEXP,
    FFN_NORM,
    FFN_PRE_NORM,
    FFN_POST_NORM,
    FFN_GATE,
    FFN_DOWN,
    FFN_UP,
    FFN_ACT,
    FFN_NORM_EXP,
    FFN_GATE_EXP,
    FFN_DOWN_EXP,
    FFN_UP_EXP,
    FFN_GATE_SHEXP,
    FFN_DOWN_SHEXP,
    FFN_UP_SHEXP,
    FFN_EXP_PROBS_B,
    ATTN_Q_NORM,
    ATTN_K_NORM,
    LAYER_OUT_NORM,
    SSM_IN,
    SSM_CONV1D,
    SSM_X,
    SSM_DT,
    SSM_A,
    SSM_D,
    SSM_OUT,
    TIME_MIX_W1,
    TIME_MIX_W2,
    TIME_MIX_LERP_X,
    TIME_MIX_LERP_K,
    TIME_MIX_LERP_V,
    TIME_MIX_LERP_R,
    TIME_MIX_LERP_G,
    TIME_MIX_LERP_W,
    TIME_MIX_FIRST,
    TIME_MIX_DECAY,
    TIME_MIX_DECAY_W1,
    TIME_MIX_DECAY_W2,
    TIME_MIX_KEY,
    TIME_MIX_VALUE,
    TIME_MIX_RECEPTANCE,
    TIME_MIX_GATE,
    TIME_MIX_LN,
    TIME_MIX_OUTPUT,
    CHANNEL_MIX_LERP_K,
    CHANNEL_MIX_LERP_R,
    CHANNEL_MIX_KEY,
    CHANNEL_MIX_RECEPTANCE,
    CHANNEL_MIX_VALUE,
    ATTN_Q_A,
    ATTN_Q_B,
    ATTN_KV_A_MQA,
    ATTN_KV_B,
    ATTN_Q_A_NORM,
    ATTN_KV_A_NORM,
    FFN_SUB_NORM,
    ATTN_SUB_NORM,
    DEC_ATTN_NORM,
    DEC_ATTN_Q,
    DEC_ATTN_K,
    DEC_ATTN_V,
    DEC_ATTN_OUT,
    DEC_ATTN_REL_B,
    DEC_CROSS_ATTN_NORM,
    DEC_CROSS_ATTN_Q,
    DEC_CROSS_ATTN_K,
    DEC_CROSS_ATTN_V,
    DEC_CROSS_ATTN_OUT,
    DEC_CROSS_ATTN_REL_B,
    DEC_FFN_NORM,
    DEC_FFN_GATE,
    DEC_FFN_DOWN,
    DEC_FFN_UP,
    DEC_OUTPUT_NORM,
    ENC_ATTN_NORM,
    ENC_ATTN_Q,
    ENC_ATTN_K,
    ENC_ATTN_V,
    ENC_ATTN_OUT,
    ENC_ATTN_REL_B,
    ENC_FFN_NORM,
    ENC_FFN_GATE,
    ENC_FFN_DOWN,
    ENC_FFN_UP,
    ENC_OUTPUT_NORM,
    CLS, // classifier
    CLS_OUT, // classifier output projection
    CONV1D,
    CONVNEXT_DW,
    CONVNEXT_NORM,
    CONVNEXT_PW1,
    CONVNEXT_PW2,
    CONVNEXT_GAMMA,
    POSNET_CONV1,
    POSNET_CONV2,
    POSNET_NORM,
    POSNET_NORM1,
    POSNET_NORM2,
    POSNET_ATTN_NORM,
    POSNET_ATTN_Q,
    POSNET_ATTN_K,
    POSNET_ATTN_V,
    POSNET_ATTN_OUT,
};

pub const TensorNames = struct {
    const Self = @This();

    pub const map = std.enums.EnumMap(ModelTensor, []const u8).init(.{
        .TOKEN_EMBD = "token_embd",
        .TOKEN_EMBD_NORM = "token_embd_norm",
        .TOKEN_TYPES = "token_types",
        .POS_EMBD = "position_embd",
        .OUTPUT_NORM = "output_norm",
        .OUTPUT = "output",
        .ROPE_FREQS = "rope_freqs",
        .ROPE_FACTORS_LONG = "rope_factors_long",
        .ROPE_FACTORS_SHORT = "rope_factors_short",
        .ATTN_NORM = "blk.{bid}.attn_norm",
        .ATTN_NORM_2 = "blk.{bid}.attn_norm_2",
        .ATTN_QKV = "blk.{bid}.attn_qkv",
        .ATTN_Q = "blk.{bid}.attn_q",
        .ATTN_K = "blk.{bid}.attn_k",
        .ATTN_V = "blk.{bid}.attn_v",
        .ATTN_OUT = "blk.{bid}.attn_output",
        .ATTN_ROT_EMBD = "blk.{bid}.attn_rot_embd",
        .ATTN_Q_NORM = "blk.{bid}.attn_q_norm",
        .ATTN_K_NORM = "blk.{bid}.attn_k_norm",
        .ATTN_OUT_NORM = "blk.{bid}.attn_output_norm",
        .ATTN_POST_NORM = "blk.{bid}.post_attention_norm",
        .FFN_GATE_INP = "blk.{bid}.ffn_gate_inp",
        .FFN_GATE_INP_SHEXP = "blk.{bid}.ffn_gate_inp_shexp",
        .FFN_NORM = "blk.{bid}.ffn_norm",
        .FFN_PRE_NORM = "blk.{bid}.ffn_norm",
        .FFN_POST_NORM = "blk.{bid}.post_ffw_norm",
        .FFN_GATE = "blk.{bid}.ffn_gate",
        .FFN_DOWN = "blk.{bid}.ffn_down",
        .FFN_UP = "blk.{bid}.ffn_up",
        .FFN_GATE_SHEXP = "blk.{bid}.ffn_gate_shexp",
        .FFN_DOWN_SHEXP = "blk.{bid}.ffn_down_shexp",
        .FFN_UP_SHEXP = "blk.{bid}.ffn_up_shexp",
        .FFN_ACT = "blk.{bid}.ffn",
        .FFN_NORM_EXP = "blk.{bid}.ffn_norm_exps",
        .FFN_GATE_EXP = "blk.{bid}.ffn_gate_exps",
        .FFN_DOWN_EXP = "blk.{bid}.ffn_down_exps",
        .FFN_UP_EXP = "blk.{bid}.ffn_up_exps",
        .FFN_EXP_PROBS_B = "blk.{bid}.exp_probs_b",
        .LAYER_OUT_NORM = "blk.{bid}.layer_output_norm",
        .SSM_IN = "blk.{bid}.ssm_in",
        .SSM_CONV1D = "blk.{bid}.ssm_conv1d",
        .SSM_X = "blk.{bid}.ssm_x",
        .SSM_DT = "blk.{bid}.ssm_dt",
        .SSM_A = "blk.{bid}.ssm_a",
        .SSM_D = "blk.{bid}.ssm_d",
        .SSM_OUT = "blk.{bid}.ssm_out",
        .TIME_MIX_W1 = "blk.{bid}.time_mix_w1",
        .TIME_MIX_W2 = "blk.{bid}.time_mix_w2",
        .TIME_MIX_LERP_X = "blk.{bid}.time_mix_lerp_x",
        .TIME_MIX_LERP_K = "blk.{bid}.time_mix_lerp_k",
        .TIME_MIX_LERP_V = "blk.{bid}.time_mix_lerp_v",
        .TIME_MIX_LERP_R = "blk.{bid}.time_mix_lerp_r",
        .TIME_MIX_LERP_G = "blk.{bid}.time_mix_lerp_g",
        .TIME_MIX_LERP_W = "blk.{bid}.time_mix_lerp_w",
        .TIME_MIX_FIRST = "blk.{bid}.time_mix_first",
        .TIME_MIX_DECAY = "blk.{bid}.time_mix_decay",
        .TIME_MIX_DECAY_W1 = "blk.{bid}.time_mix_decay_w1",
        .TIME_MIX_DECAY_W2 = "blk.{bid}.time_mix_decay_w2",
        .TIME_MIX_KEY = "blk.{bid}.time_mix_key",
        .TIME_MIX_VALUE = "blk.{bid}.time_mix_value",
        .TIME_MIX_RECEPTANCE = "blk.{bid}.time_mix_receptance",
        .TIME_MIX_GATE = "blk.{bid}.time_mix_gate",
        .TIME_MIX_LN = "blk.{bid}.time_mix_ln",
        .TIME_MIX_OUTPUT = "blk.{bid}.time_mix_output",
        .CHANNEL_MIX_LERP_K = "blk.{bid}.channel_mix_lerp_k",
        .CHANNEL_MIX_LERP_R = "blk.{bid}.channel_mix_lerp_r",
        .CHANNEL_MIX_KEY = "blk.{bid}.channel_mix_key",
        .CHANNEL_MIX_RECEPTANCE = "blk.{bid}.channel_mix_receptance",
        .CHANNEL_MIX_VALUE = "blk.{bid}.channel_mix_value",
        .ATTN_Q_A = "blk.{bid}.attn_q_a",
        .ATTN_Q_B = "blk.{bid}.attn_q_b",
        .ATTN_KV_A_MQA = "blk.{bid}.attn_kv_a_mqa",
        .ATTN_KV_B = "blk.{bid}.attn_kv_b",
        .ATTN_Q_A_NORM = "blk.{bid}.attn_q_a_norm",
        .ATTN_KV_A_NORM = "blk.{bid}.attn_kv_a_norm",
        .ATTN_SUB_NORM = "blk.{bid}.attn_sub_norm",
        .FFN_SUB_NORM = "blk.{bid}.ffn_sub_norm",
        .DEC_ATTN_NORM = "dec.blk.{bid}.attn_norm",
        .DEC_ATTN_Q = "dec.blk.{bid}.attn_q",
        .DEC_ATTN_K = "dec.blk.{bid}.attn_k",
        .DEC_ATTN_V = "dec.blk.{bid}.attn_v",
        .DEC_ATTN_OUT = "dec.blk.{bid}.attn_o",
        .DEC_ATTN_REL_B = "dec.blk.{bid}.attn_rel_b",
        .DEC_CROSS_ATTN_NORM = "dec.blk.{bid}.cross_attn_norm",
        .DEC_CROSS_ATTN_Q = "dec.blk.{bid}.cross_attn_q",
        .DEC_CROSS_ATTN_K = "dec.blk.{bid}.cross_attn_k",
        .DEC_CROSS_ATTN_V = "dec.blk.{bid}.cross_attn_v",
        .DEC_CROSS_ATTN_OUT = "dec.blk.{bid}.cross_attn_o",
        .DEC_CROSS_ATTN_REL_B = "dec.blk.{bid}.cross_attn_rel_b",
        .DEC_FFN_NORM = "dec.blk.{bid}.ffn_norm",
        .DEC_FFN_GATE = "dec.blk.{bid}.ffn_gate",
        .DEC_FFN_DOWN = "dec.blk.{bid}.ffn_down",
        .DEC_FFN_UP = "dec.blk.{bid}.ffn_up",
        .DEC_OUTPUT_NORM = "dec.output_norm",
        .ENC_ATTN_NORM = "enc.blk.{bid}.attn_norm",
        .ENC_ATTN_Q = "enc.blk.{bid}.attn_q",
        .ENC_ATTN_K = "enc.blk.{bid}.attn_k",
        .ENC_ATTN_V = "enc.blk.{bid}.attn_v",
        .ENC_ATTN_OUT = "enc.blk.{bid}.attn_o",
        .ENC_ATTN_REL_B = "enc.blk.{bid}.attn_rel_b",
        .ENC_FFN_NORM = "enc.blk.{bid}.ffn_norm",
        .ENC_FFN_GATE = "enc.blk.{bid}.ffn_gate",
        .ENC_FFN_DOWN = "enc.blk.{bid}.ffn_down",
        .ENC_FFN_UP = "enc.blk.{bid}.ffn_up",
        .ENC_OUTPUT_NORM = "enc.output_norm",
        .CLS = "cls",
        .CLS_OUT = "cls.output",
        .CONV1D = "conv1d",
        .CONVNEXT_DW = "convnext.{bid}.dw",
        .CONVNEXT_NORM = "convnext.{bid}.norm",
        .CONVNEXT_PW1 = "convnext.{bid}.pw1",
        .CONVNEXT_PW2 = "convnext.{bid}.pw2",
        .CONVNEXT_GAMMA = "convnext.{bid}.gamma",
        .POSNET_CONV1 = "posnet.{bid}.conv1",
        .POSNET_CONV2 = "posnet.{bid}.conv2",
        .POSNET_NORM = "posnet.{bid}.norm",
        .POSNET_NORM1 = "posnet.{bid}.norm1",
        .POSNET_NORM2 = "posnet.{bid}.norm2",
        .POSNET_ATTN_NORM = "posnet.{bid}.attn_norm",
        .POSNET_ATTN_Q = "posnet.{bid}.attn_q",
        .POSNET_ATTN_K = "posnet.{bid}.attn_k",
        .POSNET_ATTN_V = "posnet.{bid}.attn_v",
        .POSNET_ATTN_OUT = "posnet.{bid}.attn_output",
    });

    pub fn get(arch: ModelArch) []const u8 {
        return map.get(arch).?;
    }
};
