pub const CommonGrammarTriggerType = enum {
    COMMON_GRAMMAR_TRIGGER_TYPE_TOKEN,
    COMMON_GRAMMAR_TRIGGER_TYPE_WORD,
    COMMON_GRAMMAR_TRIGGER_TYPE_PATTERN,
    COMMON_GRAMMAR_TRIGGER_TYPE_PATTERN_START,
};

pub const common_sampler_type = enum {
    COMMON_SAMPLER_TYPE_NONE,
    COMMON_SAMPLER_TYPE_DRY,
    COMMON_SAMPLER_TYPE_TOP_K,
    COMMON_SAMPLER_TYPE_TOP_P,
    COMMON_SAMPLER_TYPE_MIN_P,
    //COMMON_SAMPLER_TYPE_TFS_Z       ,
    COMMON_SAMPLER_TYPE_TYPICAL_P,
    COMMON_SAMPLER_TYPE_TEMPERATURE,
    COMMON_SAMPLER_TYPE_XTC,
    COMMON_SAMPLER_TYPE_INFILL,
    COMMON_SAMPLER_TYPE_PENALTIES,
};
