pub const llama_example = enum {
    LLAMA_EXAMPLE_COMMON,
    LLAMA_EXAMPLE_SPECULATIVE,
    LLAMA_EXAMPLE_MAIN,
    LLAMA_EXAMPLE_INFILL,
    LLAMA_EXAMPLE_EMBEDDING,
    LLAMA_EXAMPLE_PERPLEXITY,
    LLAMA_EXAMPLE_RETRIEVAL,
    LLAMA_EXAMPLE_PASSKEY,
    LLAMA_EXAMPLE_IMATRIX,
    LLAMA_EXAMPLE_BENCH,
    LLAMA_EXAMPLE_SERVER,
    LLAMA_EXAMPLE_CVECTOR_GENERATOR,
    LLAMA_EXAMPLE_EXPORT_LORA,
    LLAMA_EXAMPLE_LLAVA,
    LLAMA_EXAMPLE_LOOKUP,
    LLAMA_EXAMPLE_PARALLEL,
    LLAMA_EXAMPLE_TTS,
    LLAMA_EXAMPLE_COUNT,
};

pub const common_sampler_type = enum {
    COMMON_SAMPLER_TYPE_NONE,
    COMMON_SAMPLER_TYPE_DRY,
    COMMON_SAMPLER_TYPE_TOP_K,
    COMMON_SAMPLER_TYPE_TOP_P,
    COMMON_SAMPLER_TYPE_MIN_P,
    COMMON_SAMPLER_TYPE_TYPICAL_P,
    COMMON_SAMPLER_TYPE_TEMPERATURE,
    COMMON_SAMPLER_TYPE_XTC,
    COMMON_SAMPLER_TYPE_INFILL,
    COMMON_SAMPLER_TYPE_PENALTIES,
};

pub const common_reasoning_format = enum {
    COMMON_REASONING_FORMAT_NONE,
    COMMON_REASONING_FORMAT_DEEPSEEK,
};
pub const dimre_method = enum {
    DIMRE_METHOD_PCA,
    DIMRE_METHOD_MEAN,
};

pub const common_conversation_mode = enum {
    COMMON_CONVERSATION_MODE_DISABLED,
    COMMON_CONVERSATION_MODE_ENABLED,
    COMMON_CONVERSATION_MODE_AUTO,
};

pub const common_grammar_trigger_type = enum {
    COMMON_GRAMMAR_TRIGGER_TYPE_TOKEN,
    COMMON_GRAMMAR_TRIGGER_TYPE_WORD,
    COMMON_GRAMMAR_TRIGGER_TYPE_PATTERN,
    COMMON_GRAMMAR_TRIGGER_TYPE_PATTERN_START,
};
