name: Build and Release zLLM

on:
  push:
    tags:
      - "v*.*.*" 

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        include:
          - os: ubuntu-22.04
            artifact_name: zLLM
            archive_name: zLLM-linux.tar.gz
          - os: macos-latest
            artifact_name: zLLM
            archive_name: zLLM-macos.zip

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2

      - name: Build Release
        run: zig build -DReleaseFast

      - name: Package Binary
        run: |
          mkdir -p dist
          cp zig-out/bin/${{ matrix.artifact_name }} dist/

          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            zip -j dist/${{ matrix.archive_name }} dist/${{ matrix.artifact_name }}
          else
            tar -czvf dist/${{ matrix.archive_name }} -C dist ${{ matrix.artifact_name }}
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive_name }}
          path: dist/${{ matrix.archive_name }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
